<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SimulationSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $simulations = [
            // Chapitre 1 : La reproduction humaine
            [
                'titre' => 'Observation microscopique de spermatozoïdes',
                'description' => 'Observer les spermatozoïdes au microscope virtuel.',
                'chapitre' => 'La reproduction humaine',
                'date' => '2025-06-01',
                'type_simulation' => 'THREEJS',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Simulation de la fécondation',
                'description' => 'Voir la rencontre entre un spermatozoïde et un ovule, et la formation du zygote.',
                'chapitre' => 'La reproduction humaine',
                'date' => '2025-06-01',
                'type_simulation' => 'UNITY',
                'contexte' => 'maison',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Reconstitution des étapes du cycle menstruel',
                'description' => 'Suivre l’évolution du cycle hormonal féminin avec animation.',
                'chapitre' => 'La reproduction humaine',
                'date' => '2025-06-01',
                'type_simulation' => 'HTML5',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Utilisation de tests de grossesse (virtuellement)',
                'description' => 'Simuler un test de grossesse et interpréter les résultats.',
                'chapitre' => 'La reproduction humaine',
                'date' => '2025-06-01',
                'type_simulation' => 'HTML5',
                'contexte' => 'maison',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Influence des hormones sur les organes reproducteurs',
                'description' => 'Visualiser l’effet des hormones sur les organes reproducteurs au cours du cycle.',
                'chapitre' => 'La reproduction humaine',
                'date' => '2025-06-01',
                'type_simulation' => 'UNITY',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Chapitre 2 : La respiration cellulaire
            [
                'titre' => 'Consommation d’oxygène et rejet de CO₂',
                'description' => 'Observer la respiration cellulaire via levures ou graines en germination.',
                'chapitre' => 'La respiration cellulaire',
                'date' => '2025-06-01',
                'type_simulation' => 'HTML5',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Visualisation d\'une cellule active',
                'description' => 'Montrer les mitochondries et leur rôle dans la production d’énergie.',
                'chapitre' => 'La respiration cellulaire',
                'date' => '2025-06-01',
                'type_simulation' => 'UNITY',
                'contexte' => 'maison',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Transport de l’O₂ et du CO₂ dans le sang',
                'description' => 'Suivre le trajet des gaz dans les globules rouges à travers le corps.',
                'chapitre' => 'La respiration cellulaire',
                'date' => '2025-06-01',
                'type_simulation' => 'THREEJS',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Chapitre 3 : La digestion des aliments
            [
                'titre' => 'Action de la salive sur l’amidon',
                'description' => 'Observer la transformation de l’amidon en glucose grâce à l’amylase salivaire.',
                'chapitre' => 'La digestion des aliments',
                'date' => '2025-06-01',
                'type_simulation' => 'HTML5',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Transformation des aliments dans les organes digestifs',
                'description' => 'Suivre chaque étape de la digestion dans la bouche, estomac et intestin.',
                'chapitre' => 'La digestion des aliments',
                'date' => '2025-06-01',
                'type_simulation' => 'UNITY',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Absorption des nutriments par l’intestin',
                'description' => 'Explorer les villosités intestinales et le passage dans le sang.',
                'chapitre' => 'La digestion des aliments',
                'date' => '2025-06-01',
                'type_simulation' => 'HTML5',
                'contexte' => 'maison',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Rôle des enzymes digestives',
                'description' => 'Tester différentes enzymes digestives sur les aliments (simulation in vitro).',
                'chapitre' => 'La digestion des aliments',
                'date' => '2025-06-01',
                'type_simulation' => 'THREEJS',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Chapitre 4 : La circulation sanguine
            [
                'titre' => 'Circulation dans un cœur humain',
                'description' => 'Visualiser le fonctionnement du cœur humain en 3D.',
                'chapitre' => 'La circulation sanguine',
                'date' => '2025-06-01',
                'type_simulation' => 'UNITY',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Trajet du sang dans les cavités du cœur',
                'description' => 'Explorer le trajet du sang dans les oreillettes et ventricules.',
                'chapitre' => 'La circulation sanguine',
                'date' => '2025-06-01',
                'type_simulation' => 'HTML5',
                'contexte' => 'maison',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Suivi du sang dans la double circulation',
                'description' => 'Suivre une goutte de sang à travers la petite et grande circulation.',
                'chapitre' => 'La circulation sanguine',
                'date' => '2025-06-01',
                'type_simulation' => 'HTML5',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'titre' => 'Simulation d’un électrocardiogramme',
                'description' => 'Observer un ECG en temps réel pour comprendre l’activité cardiaque.',
                'chapitre' => 'La circulation sanguine',
                'date' => '2025-06-01',
                'type_simulation' => 'THREEJS',
                'contexte' => 'classe',
                'lien_meet' => null,
                'notification_envoyee' => 0,
                'professeur_id' => 1,
                'classe_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('simulations')->insert($simulations);
    }
}